dotgov-domains/2015-11-03-cities.csv, dotgov-domains/2015-11-03-counties.csv, dotgov-domains/2015-11-03-federal.csv, dotgov-domains/2015-11-03-full.csv, dotgov-domains/2015-11-03-native.csv, dotgov-domains/2015-11-03-state-local.csv
This is an update to the .gov second-level domain list, as provided by GSA's Office of Government-wide Policy, exported on November 3, 2015.
=> Adds updated second-level domain data for Nov 3, 2015

dotgov-domains/2016-01-19-cities.csv, dotgov-domains/2016-01-19-counties.csv, dotgov-domains/2016-01-19-federal.csv, dotgov-domains/2016-01-19-full.csv, dotgov-domains/2016-01-19-native.csv, dotgov-domains/2016-01-19-state-local.csv
One more update for the dotgov second-level domain list here. The `2016-01-19-full.csv` file should soon be matched with an update to Data.gov with all appropriate metadata, at which point we should be able to deprecate or close this repo and redirect people to that entry.
=> Updated domain data for 2016-01-19

README.md
* Last link in README pointing to an alternative map by Tyler Shimko is broken.
* Checked the user's site, blog has been ported to medium, map no longer exists.
* Subsequently removed link
=> remove broken link from README

dotgov-domains/2016-06-30-city.csv, dotgov-domains/2016-06-30-counties.csv, dotgov-domains/2016-06-30-federal.csv, dotgov-domains/2016-06-30-full.csv, dotgov-domains/2016-06-30-native.csv, dotgov-domains/2016-06-30-state-local.csv, dotgov-domains/current-full.csv
This updates the .gov domain dataset for June 30th, 2016.
Two things worth noting here:
* I have copied `2016-06-30-full.csv` to `current-full.csv`. In future updates (for as long as this repository continues getting updates -- I'd still love for data.gov to become canonical and current), I'll keep overwriting `current-full.csv` with the latest data. This means that there's a single consistent permalink, and downstream users can code it once and forget about it.
* This dataset not only includes added and removed domains since the last update (2016-05-02), but also some additional domains that were not included in this dataset until recently. These additional domains include many of the domains seen in the response data provided by GSA via @thejefflarson's FOIA appeal, which @thejefflarson …
=> Updated domain data for 2016-06-30

dotgov-domains/current-federal.csv
In addition to `current-full.csv`, this adds a `current-federal.csv`. I don't yet see the need to break it down to other specific categories, and I kind of regret setting that precedent in earlier data updates. But [Pulse](https://pulse.cio.gov) is at least one major data consumer that benefits directly from a federal-only spreadsheet, and given the federal government's unique role and scope, it seems to make sense.
=> Add a current permalink to just federal domains

enterprise-architecture/README.md
The column is easy to miss otherwise.
=> call out the IT Standards Status column

dotgov-websites/censys-federal-snapshot.csv
This removes two bad hostnames from the Censys snapshot as a quick fix:
```
dns name=trainingprism-test.dhs.gov
dns name=trainingprism.dhs.gov
```
See https://github.com/18F/domain-scan/issues/200 for the issue tracking fixing the underlying cause.
Fixes #112.
=> Remove two bad "dns name" hostnames from the Censys snapshot

dotgov-domains/current-federal.csv, dotgov-domains/current-full.csv
Old names are red / New names are green / .gov is great / It's March
Of note:
* The return of `askkaren.gov` from its temporary sleep and the re-alignment of `usip.gov` from GSA ownership to USIP directly.
* Aligning domains with "county" in their name with the County domain type
=> Updating .gov list from 2018-03-02

dotgov-domains/current-federal.csv, dotgov-domains/current-full.csv
This update include a number of changes to current-federal :us::
* more accurately captures the names of federal agencies as they call themselves (e.g., "U.S. Department of Agriculture" rather than "Department of Agriculture")
* fixes a few errors (e.g., "United Stated")
* cleans up place names (e.g., "Washington" is the city, "DC" is the "state", instead of `Washington D.C., DC`, `Washington DC, DC`; `WASHINGTON, DC`)
=> Updating .gov list from March 27 2018

dotgov-websites/other-websites.csv
DOI asked NCATS to add to the HTTPS and Trustworthy Email report scanning.  I verified that these hosts were not being picked up through other means.
=> Adding some extra hosts

dotgov-domains/current-federal.csv, dotgov-domains/current-full.csv
In addition to laying out new and retired domains, this change brings new data! 🎉 
* replacing the `Federal Agency` domain type thrice over (#129)
* `Federal Agency - Executive`
* `Federal Agency - Judicial`
* `Federal Agency - Legislative`
* adding the `Organization` field (#33). This data was previously only viewable in the [DotGov whois](https://domains.dotgov.gov/dotgov-web/registration/whois.xhtml). This data is interesting, but pretty messy at present.
Stepped commits show the incremental changes to both current-full and current-federal.
=> Updating .gov list from April 26, 2018; adding gov branches, org field

dotgov-websites/other-websites.csv
This was being excluded through a fault of the code (anything prefixed with `domain`).
=> Removing domains.dotgov.gov from other-websites.csv

dotgov-websites/other-websites.csv
Adding two hosts that DOI requested be scanned by DHS' HTTPS and Trustworthy Email scanning.  These hosts are not currently being gathered by other means.
=> Adding two hosts for DOI

dotgov-domains/current-federal.csv, dotgov-domains/current-full.csv
In addition to the new/retired domains, this change adds an `Interstate` domain type and recategorizes several domains. From our [domain requirements write-up](https://home.dotgov.gov/registration/requirements/#interstate-domains): 
>Interstate governmental organizations are most frequently formed via legislation from Congress or from a legal accord between the state governments of two or more states.
=> Updating .gov list from May 21, 2018; add Interstate domains

dotgov-domains/current-federal.csv, dotgov-domains/current-full.csv
Quick release, mostly to account for the deletion of several GSA test domains.
=> Updating .gov list from May 25, 2018

dotgov-domains/current-federal.csv, dotgov-domains/current-full.csv
This fixes a subtle regression in https://github.com/GSA/data/pull/147#pullrequestreview-124477848 where a Unicode character was introduced as the first character in the two domain CSV files, which can cause issues in CSV parsers.
I used `nano` to make the edits, which also added a blank newline at the end of the file, which is pretty standard (and generally recommended) anyway.
I verified that the fixed files parse properly in at least one parser that was failing previously (Pulse).
=> Fix Unicode character issue in CSV header rows

dotgov-websites/other-websites.csv
This adds `email` and `calendar` aliases for GSA and NARA G Suite instances.
=> Adding a couple of email/calendar G Suite aliases

dotgov-domains/current-federal.csv, dotgov-domains/current-full.csv
Along with a new federal domain (apprenticeships.gov) and some non-federals (notably, chicago.gov), there are a few data cleanliness efforts afoot.
=> Updating .gov list from June 22, 2018

dotgov-websites/other-websites.csv
See NCATS JIRA ticket OPS-2709 for details.
=> Adding the domain openforest.fs.usda.gov for USDA

dotgov-websites/other-websites.csv
Adds ug.roc.noaa.gov to the manual list.
=> Adding a hostname as requested by NOAA

dotgov-websites/ocsp-crl.csv
This starts a CSV file with manually marked OCSP-only or CRL-only hostnames, for those services that meet the [OCSP/CRL exclusion](https://https.cio.gov/guide/#are-federally-operated-certificate-revocation-services-crl-ocsp-also-required-to-move-to-https) in M-15-13 and BOD 18-01.
To start, it's a few self-reported hosts within llnl.gov.
I think it will be important to be strict about only adding services which are reserved principally for production OCSP/CRL services. Dev/staging sites that may also dual-host content, for example, would not be appropriate to add here, nor would any other service that an agency might believe merits exemption on the grounds of being unimportant or not "public-facing".
=> Create a CSV file tracking OCSP/CRL sites

dotgov-websites/ocsp-crl.csv
These two sites should be added to the OCSP/CRL list so that Department of State does not get pinged for them not being compliant with BOD 18-01.
=> Add two Department of State OCSP/CRL sites

dotgov-websites/ocsp-crl.csv
The following three hosts should be added to the OCSP list for exclusion from HTTPS Compliance evaluation:
hc.nasa.gov
ocsp.nasa.gov
ocsp-rra.ndc.nasa.gov
=> Add 3 NASA OCSP Hosts

dotgov-websites/other-websites.csv
HHS has requested that search.uspreventiveservicestaskforce.org.  Confirmed that HHS/AHRQ maintains the entire uspreventiveservicestaskforce.org namespace.
=> Add a few non-.gov sites for HHS and an hhs.gov subdomain

dotgov-websites/other-websites.csv
Please add these 9 uspis.gov subdomains for USPS since they aren't being reported within their HTTPS/Tmail reports.
=> Adding 9 uspis.gov subdomains

dotgov-websites/other-websites.csv
Please add nrmcanalysis.dhs.gov so that it shows up in DHS' HTTPS and Tmail reports.
=> Add a CISA domain for DHS BOD reporting

dotgov-websites/ocsp-crl.csv
DOC has reported that the added 7 USPTO IPKI URLs have been configured per RFC standards (RFC 5280 & RFC6960)and should be out of scope for HTTPS/HSTS checks according to https://https.cio.gov/guide/#are-federally-operated-certificate-revocation-services-crl-ocsp-also-required-to-move-to-https.
=> Add 7 domains for DOC

dotgov-websites/other-websites.csv
HHS noticed that some domains are missing from their HTTPS/Tmail reports, and would like to request that the 7 added to this list be included in their weekly reports.
=> Add 7 subdomains for HHS/CDC

dotgov-websites/other-websites.csv
VA has reached out to ask if we can scan care2.va.gov, which isn't currently included in the reports we send them.
=> Add a new website for VA

dotgov-websites/ocsp-crl.csv
VA has requested this domain be marked out of scope for their HTTPS compliance report.
=> Adding VA OCSP/PKI Domain

dotgov-websites/other-websites.csv
Per USAID's request, they request to add this domain to their scope for HTTPS and Trustworthy Email compliance reports.
=> Adding USAID Domain

dotgov-websites/other-websites.csv
Treasury noticed there was a difference between the count of OCSP/CRL domains listed at https://github.com/GSA/data/blob/master/dotgov-websites/ocsp-crl.csv and the number flagged as OCSP in their reports.  This is because three subs were missing.  Please add ocsp.treasury.gov, devocsp.treasury.gov, and devpki.treasury.gov so that they show up in the BOD Reports for Treasury.
=> Adding 3 Treasury Subdomains

dotgov-websites/other-websites.csv
HHS has identified a handful of subs that aren't showing up on their BOD 18-01 reports.  Please add these so that they get evaluated as part of their compliance reports :)
=> Adding a handful of HHS subdomains

dotgov-websites/other-websites.csv
Please add this subdomain so that it shows up in the DHS HTTPS/Tmail reports. Thanks!
=> Adding the new FOIA website for DHS

dotgov-websites/other-websites.csv
Requesting these DOI subdomains get added to DOI's HTTPS and Trustworthy Email reports.
=> Add subdomains for DOI

dotgov-websites/other-websites.csv
CIGIE requests these subdomains are added to their HTTPS and Trustworthy Email reports.
=> Add subdomains for CIGIE

dotgov-websites/other-websites.csv
Crossfeed has not been showing up in HTTPS/Tmail reports. Adding so that it can be checked for web and email security :)
=> Adding a subdomain for DHS

dotgov-websites/other-websites.csv
Please add wl.worklife4you.com so that it can be included in HHS' BOD 18-01 reports.
=> Adding HHS non-.gov subdomain

dotgov-websites/ocsp-crl.csv
DOC has reported 3 PKI test domains for inclusion in the OCSP/CRL list.  Please note that seclab7 is not currently live, but I figured it probably didn't hurt to add it to this list anyway.
=> Adding 3 OCSP/CRL Domains for DOC

dotgov-websites/other-websites.csv
FTC would like us to add adminefiling.ftc.gov, so that it will show up in their BOD reports.
=> Add 1 subdomain for FTC

dotgov-websites/other-websites.csv
VA has requested that we add vaitcampus.com to their HTTPS and Tmail reports.  I double checked it is a VA owned site, and a Google search of site:vaitcampus.com shows 3 subs (other than www, which will automatically be scanned): test.vaitcampus.com, specialevent.vaitcampus.com, and ui.vaitcampus.com.  Please add these to the federal "other websites" list so they show up in the VA reports.  Thank you!  :)
=> Add non-.gov and 3 subs for VA

dotgov-websites/other-websites.csv
VA has requested we add www.cep.fsc.va.gov to their HTTPS and Trustymail reports since it is not included (note: we scan all four endpoints of a domain - http, https, www-http, www-https, when we run pshtt, which is why we are only requesting the add of the non-www endpoint).
=> Add 1 subdomain for VA

dotgov-websites/ocsp-crl.csv
FHFA has requested that we add pki.fhfa.gov, dc081.fhfa.gov, and va081.fhfa.gov to the OCSP/CRL list as pki.fhfa.gov is used solely for CRL information.  The CDP url is http://pki.fhfa.gov/CertEnroll/FHFA-Sub-CA(2).crl.  Technically, dc081.fhfa.gov and va081.fhfa.gov are the actual CRL servers...pki.fhfa.gov is the CNAME that points to a load balancer which in turn balances the load to dc081.fhfa.gov and va081.fhfa.gov.
=> Add FHFA's CDPs
