- README.md
Starting with @laurenancona's from #5, and encouraging others who use the data to open issues telling us about them.
> Add unofficial public uses to the README

- README.md
Added this to be a bit more clear.  
cc @konklone
> adding note about redirecting/inactive domains

- dotgov-domains/2015-03-15-cities.csv
- dotgov-domains/2015-03-15-counties.csv
- dotgov-domains/2015-03-15-federal.csv
- dotgov-domains/2015-03-15-full.csv
- dotgov-domains/2015-03-15-native.csv
- dotgov-domains/2015-03-15-state-local.csv
An update of domain CSVs for March 2015. We hope to improve the speed and change the method of publication of this data -- months between updates here is clearly non-ideal.
> Updated domain data from March 2015

- dotgov-domains/2016-05-02-cities.csv
- dotgov-domains/2016-05-02-counties.csv
- dotgov-domains/2016-05-02-federal.csv
- dotgov-domains/2016-05-02-full.csv
- dotgov-domains/2016-05-02-native.csv
- dotgov-domains/2016-05-02-state-local.csv
An export of the .gov dataset for May 2nd, 2016.
> Updated domain data for 2016-05-02

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
This updates the .gov domain dataset with data as sent to me on February 9th, 2017 by the dotgov.gov team.
Since we removed the snapshotted data files in #54, this just overwrites `current-full.csv` and `current-federal.csv` in place.
cc @smarina04
> .gov domain update for 2017-02-09

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
The latest .gov domain list update.
> .gov domain update for 2017-05-31

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
> Updated .gov domain list for 2017-06-18

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
> .gov domain update for 2017-07-01

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
Updating the .gov domain data.
> Updating .gov domain data for August 9th, 2017

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
Updates the list of .gov domains for an export from Sep 13, 2017.
> Update list of .gov domains for 2017-09-13

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
Updates the .gov domain list for October 9, 2017.
> Update .gov domain list for 2017-10-09

- dotgov-websites/README.md
See https://github.com/GSA/data/pull/94 for the full details of the pull request.
> Added basic readme based on Pull Request details

- dotgov-websites/other-websites.csv
We got a submission of a website from an agency, to include in HTTPS reports. It's not in any of our sources. 
This PR creates a CSV that contains manually maintained websites so that we have a place to keep and pull in things that we don't know about from other automated sources.
> Adding a manually maintained file of other sites

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
Updates the list of .gov domains from an export on Feb 2nd, 2018.
> Updating .gov list from 2018-02-02

- enterprise-architecture/update.sh
> automatically show diff when updating data

- dotgov-websites/other-websites.csv
I noticed portal.dsac.gov redirected to kms.dsac.gov.
> Added kms.dsac.gov to other-websites.csv

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
EOP and GSA have done a bit of housecleaning and sent several domains to their rightful owners.
> Updating .gov list from April 13, 2018

- dotgov-websites/other-websites.csv
This isn't getting caught right now on Pulse during normal gathering.
> Adding domains.dotgov.gov

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
Restores the changes in #136, adding branches and organization fields to the .gov domains file.
> Restore organization and branch fields

- dotgov-websites/other-websites.csv
Reported by USDA, and requested to be included in reporting.
> Add some USDA-reported hosts not yet discovered

- enterprise-architecture/README.md
Sean Zergess, who will be updating it, is using Windows, so won't have an easy way to do the updating via script.
> re-add the manual steps for updating the IT Standards data

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
Sweet Home, my Portland
Apprenticeship sails rise, my
Education sets
> Updating .gov list from June 7, 2017

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
Updates the list of .gov domains from an export on July 16, 2018.
> Updating .gov list from July 16, 2018

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
This update adds several domains that are new to this dataset.
> Updating .gov list from July 23, 2018

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
Updating the .gov list! New federal domains are ai.gov, usagm.gov.
> Updating .gov list from August 17, 2018

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
Two new federal additions: mimm.gov and joinamericorps.gov.
> Updating .gov list from August 31, 2018

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
One new USG .gov (hig.gov, which belongs to DOJ) and a bunch of new state and local domains.
> Sept 17 update

- dotgov-websites/other-websites.csv
See NCATS JIRA ticket OPS-2895 for details.
> Add two domains for DOE

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
This is a .gov public service announcement: a pull of all .gov domains from Monday, October 1, 2018.
> Oct 1 2018 update

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
ehr.gov is new for VA; some new SLTT and interstate domains, too.
> Update from Oct 25 2018

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
An update from an export of domains from the .gov registrar.
> Update from November 13 2018

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
An update pulled from the .gov registrar, December 3, 2018.
> Update from December 3, 2018

- dotgov-websites/other-websites.csv
As reported to Pulse from NOAA.
> Adding a NOAA site to the websites list

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
Updating .gov domains from a registrar export, 6 Feb 2019.
> Update from February 6, 2019

- dotgov-websites/other-websites.csv
See NCATS JIRA ticket OPS-3454 for details.
> Add four domains for SSA

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
New domains added and steady growth in security contacts.
> Update from May 6 2019

- dotgov-websites/other-websites.csv
Added an additional treasury subdomain.
> Added new Treasury subdomain.

- dotgov-websites/other-websites.csv
See NCATS JIRA ticket CYHYOPS-4714 for details.
> Added an additional domains for TSA

- dotgov-websites/other-websites.csv
HHS has requested these be added to their HTTPS/Tmail reports.
> Add 10 non-.gov's for HHS/NIH

- dotgov-websites/other-websites.csv
Please add this website for CIGIE so that it can show up in their HTTPS/Tmail reports. Thanks!
> Add a new website for CIGIE

- dotgov-websites/other-websites.csv
Please add this domain to HHS's HTTPS and Trustworthy Email compliance reports.
> Adding HHS Domain

- dotgov-websites/other-websites.csv
FRTIB requested this domain be added to their HTTPS/Tmail reports
> Add new subdomain for FRTIB

- dotgov-websites/other-websites.csv
Please add these two HHS subdomains so that they can be reported within HHS' HTTPS and Tmail reports.  Thanks!
> Adding two HHS Subdomains

- dotgov-websites/other-websites.csv
CFPB requested this subdomain get added to their HTTPS/Tmail reports.
> Add subdomain for CFPB

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
This PR updates the .gov domain list from an export of the .gov registrar on March 15, 2021.
> Update from March 15 2021

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
We may not `bebest.gov` nor the `firstresponder.gov` but we strive for a `saferfederalworkforce.gov`.
> Update from March 22 2021

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
BBB moves to EOP, Idaho votes.
> Update from March 29, 2021

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
Domain updates from .gov-using US-based government organizations.
> Update from April 5, 2021

- dotgov-domains/current-federal.csv
- dotgov-domains/current-full.csv
Everyone loves domain updates! Here's one from today.
> Update from April 12, 2021
